<footer>
  <nav>
    <div class="footer-container">
      <div class="footer-column">
        <h2 class="footer-column-title">Pages</h2>
        <ul class="footer-column-list">
          <li class="footer-column-item">
            <a href="./index.php">Home</a>
          </li>
          <li class="footer-column-item">
            <a href="./jobs.php">Job Description</a>
          </li>
          <li class="footer-column-item">
            <a href="./apply.php">Apply</a>
          </li>
          <li class="footer-column-item">
            <a href="./about.php">About</a>
          </li>
        </ul>
      </div>
      <div class="footer-column">
        <h2 class="footer-column-title">Resources</h2>
        <ul class="footer-column-list">
          <li class="footer-column-item">
            <a href="https://github.com/mqypr/UrbanSync">Github Repository</a>
          </li>
          <li class="footer-column-item">
            <a class="footer-column-item"
              href="https://pengreach123.atlassian.net/?continue=https%3A%2F%2Fpengreach123.atlassian.net%2Fwelcome%2Fsoftware%3FprojectId%3D10033&atlOrigin=eyJpIjoiOGMzNTY2NzRmYTE2NGY5MzkxNmFkNDQ3ZmFmNWVmYmYiLCJwIjoiamlyYS1zb2Z0d2FyZSJ9">Jira
            </a>
          </li>
          <li class="footer-column-item">
            <a class="footer-column-item" href="https://mqypr.github.io/UrbanSync/">Live Link</a>
          </li>
        </ul>
      </div>
      <div class="footer-column">
        <h2 class="footer-column-title">Contact Us</h2>
        <ul class="footer-column-list">
          <li class="footer-column-item">
            <a href="mailto:hello@urbansync.com.au" class="footer-column-item">Email</a>
          </li>
        </ul>
      </div>
    </div>

  </nav>
</footer>