<header>
  <nav class="navbar">
    <div class="navbar-container">
      <!--navbar logo links to index page-->
      <div class="navbar-logo">
        <a href="index.php"><img src="./images/logo.png" class="logo-pic" alt="logo-pic"></a>
      </div>
      <!--navbar links to other pages-->
      <div class="navbar-link">
        <a href="./jobs.php" class="navbar-link-item">JOB DESCRIPTION</a>
        <a href="./apply.php" class="navbar-link-item">APPLY</a>
        <a href="./about.php" class="navbar-link-item">ABOUT</a>
        <div class="navbar-settings">
          <button class="navbar-link-item">ACCOUNT</button>
          <div class="navbar-settings-dropdown-content">
            <a href="./login.php" class="navbar-link-item-settings">LOGIN</a>
            <label class="switch">
              <input type="checkbox">
              <span class="slider round"></span>
            </label>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>