<header>
  <nav class="navbar">
    <div class="navbar-container">
      <!--navbar logo links to index page-->
      <div class="navbar-logo">
        <a href="index.php"><img src="./images/logo.png" class="logo-pic" alt="logo-pic"></a>
      </div>
      <!--navbar links to other pages-->
      <div class="navbar-link">
        <a href="jobs.php" class="navbar-link-item-a">JOB DESCRIPTION</a>
        <a href="apply.php" class="navbar-link-item-a">APPLY</a>
        <a href="about.php" class="navbar-link-item-a">ABOUT</a>
      </div>
    </div>
  </nav>
</header>